import type { Plugin } from './plugin.schema.js';

export const PLUGIN_SEED_DATA: Array<Partial<Plugin>> = [
  {
    slug: 'hubspot',
    name: 'HubSpot',
    description:
      'Import contacts, companies, deals and pipelines from your HubSpot CRM for read-only analysis.',
    category: 'crm',
    mark: 'HU',
    brandColor: '#ff7a59',
    source: 'builtin',
    authType: 'oauth2',
    scopes: [
      'crm.objects.contacts.read',
      'crm.objects.companies.read',
      'crm.objects.deals.read',
    ],
    sortOrder: 10,
  },
  {
    slug: 'salesforce',
    name: 'Salesforce',
    description:
      'Pull accounts, opportunities, leads and activity from Salesforce to enrich your revenue narrative.',
    category: 'crm',
    mark: 'SF',
    brandColor: '#00a1e0',
    source: 'builtin',
    authType: 'oauth2',
    scopes: ['api', 'refresh_token'],
    sortOrder: 20,
  },
  {
    slug: 'pipedrive',
    name: 'Pipedrive',
    description:
      'Connect Pipedrive to read deals, persons, organizations and pipelines in near real time.',
    category: 'crm',
    mark: 'PI',
    brandColor: '#1b2530',
    source: 'foundry',
    authType: 'oauth2',
    scopes: ['deals:read', 'persons:read', 'organizations:read'],
    sortOrder: 30,
  },
  {
    slug: 'zoho-crm',
    name: 'Zoho CRM',
    description:
      'Sync leads, contacts, accounts and deals from Zoho CRM for revenue diagnostics.',
    category: 'crm',
    mark: 'ZO',
    brandColor: '#f0483e',
    source: 'foundry',
    authType: 'oauth2',
    scopes: ['ZohoCRM.modules.READ'],
    sortOrder: 40,
  },
  {
    slug: 'dynamics365',
    name: 'Microsoft Dynamics 365',
    description:
      'Import accounts, contacts, opportunities and marketing lists from Dynamics 365 CE.',
    category: 'crm',
    mark: 'DY',
    brandColor: '#0b53ce',
    source: 'foundry',
    authType: 'oauth2',
    scopes: ['https://dynamics.crm.analytics.read.all/user_impersonation'],
    sortOrder: 50,
  },
  {
    slug: 'freshsales',
    name: 'Freshsales',
    description:
      'Read contacts, accounts, deals and pipelines from Freshsales (Freshworks CRM).',
    category: 'crm',
    mark: 'FR',
    brandColor: '#f25e4b',
    source: 'foundry',
    authType: 'apikey',
    scopes: [],
    sortOrder: 60,
  },
  {
    slug: 'zendesk-sell',
    name: 'Zendesk Sell',
    description:
      'Fetch leads, contacts, deals and activities from Zendesk Sell for smarter forecasting.',
    category: 'crm',
    mark: 'ZE',
    brandColor: '#03363d',
    source: 'foundry',
    authType: 'oauth2',
    scopes: ['read'],
    sortOrder: 70,
  },
  {
    slug: 'monday-crm',
    name: 'Monday.com CRM',
    description:
      'Connect Monday.com boards used for your CRM to surface pipeline and activity data.',
    category: 'crm',
    mark: 'MC',
    brandColor: '#ffcb00',
    source: 'foundry',
    authType: 'oauth2',
    scopes: ['boards:read', 'workspaces:read'],
    sortOrder: 80,
  },
  {
    slug: 'copper',
    name: 'Copper',
    description:
      'Read companies, people, opportunities and activities from Copper, the Google Workspace CRM.',
    category: 'crm',
    mark: 'CO',
    brandColor: '#d05f2a',
    source: 'foundry',
    authType: 'apikey',
    scopes: [],
    sortOrder: 90,
  },
  {
    slug: 'close',
    name: 'Close',
    description:
      'Import leads, contacts, opportunities and tasks from Close for pipeline visibility.',
    category: 'crm',
    mark: 'CL',
    brandColor: '#fc5346',
    source: 'foundry',
    authType: 'apikey',
    scopes: [],
    sortOrder: 100,
  },
  {
    slug: 'hubspot-marketing',
    name: 'HubSpot Marketing',
    description:
      'Pull campaigns, email performance and marketing contact lists for revenue attribution.',
    category: 'marketing',
    mark: 'HM',
    brandColor: '#ff7a59',
    source: 'foundry',
    authType: 'oauth2',
    scopes: ['marketing.email.read', 'marketing.statistics.read'],
    sortOrder: 110,
  },
  {
    slug: 'zendesk-support',
    name: 'Zendesk Support',
    description:
      'Read tickets and customer history from Zendesk Support to connect support effort to revenue.',
    category: 'support',
    mark: 'ZS',
    brandColor: '#03363d',
    source: 'foundry',
    authType: 'oauth2',
    scopes: ['read'],
    sortOrder: 120,
  },
  {
    slug: 'stripe',
    name: 'Stripe',
    description:
      'Feed in invoices, subscriptions and MRR movements to ground revenue models in real transaction data.',
    category: 'data',
    mark: 'ST',
    brandColor: '#635bff',
    source: 'builtin',
    authType: 'manual',
    scopes: [],
    sortOrder: 130,
  },
  {
    slug: 'google-analytics',
    name: 'Google Analytics',
    description:
      'Import acquisition and conversion metrics from GA4 to map marketing spend to revenue outcomes.',
    category: 'data',
    mark: 'GA',
    brandColor: '#f9ab00',
    source: 'foundry',
    authType: 'oauth2',
    scopes: ['https://www.googleapis.com/auth/analytics.readonly'],
    sortOrder: 140,
  },
];